<?php namespace JF;
/**

Copyright 2018 JQueryForm.com
License: http://www.jqueryform.com/license.php

FormID:  jqueryform-146301
Date:    2018-11-14 21:27:41
Version: v2.1.4
Generated by http://www.jqueryform.com

PHP 5.3+ is required.
If mailgun is used AND the form has file upload field, PHP 5.5+ is required.

*/

class Config {
	private static $config;

    public static function getConfig( $decode = true ){
    	self::$config = self::_getConfig( $decode );
    	self::overwriteConfig();
    	return self::$config;
    }

    private static function _getConfig( $decode = true ){
        ob_start();
        // ---------------------------------------------------------------------
        // JSON format config
        // Note: please make a copy before you edit config manually
        // ---------------------------------------------------------------------

/**JSON_START**/ ?>
{
    "formId": "jqueryform-146301",
    "email": {
        "to": "Bobbie@hi-lite.com",
        "cc": "Dawn.Bible@hi-lite.com, ",
        "bcc": "",
        "subject": "Sample Request",
        "template": "",
        "sendmail_from": "samples@hi-litesolutions.com"
    },
    "admin": {
        "users": "admin:f03d3",
        "dataDelivery": "emailAndFile"
    },
    "thankyou": {
        "url": "",
        "message": "",
        "seconds": "10"
    },
    "autoResponse": {
        "includeAttachments": true,
        "subject": "",
        "template": ""
    },
    "seo": {
        "trackerId": "",
        "title": "",
        "description": "",
        "keywords": "",
        "author": ""
    },
    "mailer": "local",
    "smtp": {
        "host": "",
        "user": "",
        "password": ""
    },
    "mailgun": {
        "domain": "",
        "apiKey": "",
        "fromEmail": "",
        "fromName": ""
    },
    "styles": {
        "iCheck": {
            "enabled": true,
            "skin": "flat",
            "colorScheme": "black"
        },
        "Select2": {
            "enabled": true
        }
    },
    "logics": [],
    "fields": [
        {
            "label": "First Name",
            "field_type": "name",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "sender": "firstname",
                "validators": {
                    "required": {
                        "enabled": true
                    }
                }
            },
            "id": "f12",
            "cid": "c65"
        },
        {
            "label": "Last Name",
            "field_type": "name",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "sender": "lastname",
                "validators": {
                    "required": {
                        "enabled": true
                    }
                }
            },
            "cid": "c70",
            "id": "f13"
        },
        {
            "label": "Email",
            "field_type": "email",
            "field_options": {
                "size": "small",
                "sender": true,
                "images": {
                    "urls": "",
                    "slideshow": false
                },
                "validators": {
                    "email": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    }
                },
                "addon": {
                    "leftIcon": "",
                    "leftText": ""
                }
            },
            "id": "f2",
            "cid": "c2"
        },
        {
            "label": "Phone",
            "field_type": "phone",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "sender": false,
                "placeholder": "xxx-xxx-xxxx",
                "addon": {
                    "leftIcon": ""
                },
                "validators": {
                    "pattern": {
                        "enabled": true,
                        "val": "[0-9]{3,4}[ -.]*[0-9]{3,4}[ -.]*[0-9]{4}",
                        "msg": "Invalid phone number"
                    }
                }
            },
            "phone": {
                "validationMethod": "simple",
                "simpleFormat": "xxx-xxx-xxxx",
                "usePhoneLib": "N"
            },
            "id": "f4",
            "cid": "c28"
        },
        {
            "label": "Company",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "size": "small",
                "addon": []
            },
            "id": "f14",
            "cid": "c78"
        },
        {
            "label": "Address",
            "field_type": "address",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "validators": {
                    "required": {
                        "enabled": true
                    }
                }
            },
            "labelHide": false,
            "gMapApiKey": "",
            "gaCompleteEnabled": true,
            "gaCountryRestrictions": "",
            "gaPostalCodeRestrictions": "",
            "gaLanguage": "",
            "showLabel": false,
            "showPlaceholder": true,
            "showDescription": false,
            "subfields": {
                "addressLine1": {
                    "order": 1,
                    "label": "Address Line1",
                    "field_options": {
                        "enabled": true,
                        "gAddressTypes": "street_number route",
                        "gAddressName": "long_name",
                        "placeholder": "1234 Main St.",
                        "description": "Street address, P.O. box, company name, c\/o",
                        "validators": {
                            "required": {
                                "enabled": true,
                                "msg": "This field is required."
                            }
                        }
                    }
                },
                "addressLine2": {
                    "order": 2,
                    "label": "Address Line2",
                    "field_options": {
                        "enabled": false,
                        "placeholder": "Unit 1234",
                        "description": "Apartment, suite, unit, building, floor, etc.",
                        "validators": {
                            "required": {
                                "enabled": false,
                                "msg": ""
                            }
                        }
                    }
                },
                "city": {
                    "order": 3,
                    "label": "City",
                    "field_options": {
                        "enabled": true,
                        "gAddressTypes": "locality",
                        "gAddressName": "long_name",
                        "placeholder": "City",
                        "description": "City",
                        "validators": {
                            "required": {
                                "enabled": true,
                                "msg": "This field is required."
                            }
                        }
                    }
                },
                "state": {
                    "order": 4,
                    "label": "State \/ Province \/ Region",
                    "field_options": {
                        "enabled": true,
                        "gAddressTypes": "administrative_area_level_1",
                        "gAddressName": "long_name",
                        "placeholder": "State \/ Province \/ Region",
                        "description": "State \/ Province \/ Region",
                        "validators": {
                            "required": {
                                "enabled": true,
                                "msg": "This field is required."
                            }
                        }
                    }
                },
                "postalCode": {
                    "order": 5,
                    "label": "Postal \/ Zip Code",
                    "field_options": {
                        "enabled": true,
                        "gAddressTypes": "postal_code",
                        "gAddressName": "long_name",
                        "placeholder": "Postal \/ Zip Code",
                        "description": "Postal \/ Zip Code",
                        "validators": {
                            "required": {
                                "enabled": true,
                                "msg": "This field is required."
                            }
                        }
                    }
                },
                "country": {
                    "order": 6,
                    "label": "Country",
                    "field_options": {
                        "enabled": true,
                        "gAddressTypes": "country",
                        "gAddressName": "long_name",
                        "placeholder": "Country",
                        "description": "Country",
                        "validators": {
                            "required": {
                                "enabled": true,
                                "msg": "This field is required."
                            }
                        }
                    }
                }
            },
            "id": "f11",
            "cid": "c57"
        },
        {
            "label": "Sample #1",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "- None -",
                        "value": "None",
                        "checked": false
                    },
                    {
                        "label": "AG4015 Aircraft Exterior Cleaner",
                        "checked": false,
                        "value": "AG4015 Aircraft Exterior Cleaner"
                    },
                    {
                        "label": "AG4025 Airport High Pressure Cleaner",
                        "checked": false,
                        "value": "AG4025 Airport High Pressure Cleaner"
                    },
                    {
                        "label": "AG4025 Mold, Mildew and Algae Cleaner",
                        "checked": false,
                        "value": "AG4025 Mold, Mildew and Algae Cleaner"
                    },
                    {
                        "label": "AG4035 Runway Rubber Remover",
                        "value": "AG4035 Runway Rubber Remover",
                        "checked": null
                    },
                    {
                        "label": "AG4065 RTU Aircraft Exterior Cleaner",
                        "value": "AG4065 RTU Aircraft Exterior Cleaner",
                        "checked": null
                    },
                    {
                        "label": "AG4110 Paint Prep",
                        "value": "AG4110 Paint Prep",
                        "checked": null
                    },
                    {
                        "label": "AG4125 Original Cleaner-Degreaser",
                        "value": "AG4125 Original Cleaner-Degreaser",
                        "checked": null
                    },
                    {
                        "label": "AG4130 High Pressure Cleaner-Degreaser",
                        "value": "AG4130 High Pressure Cleaner-Degreaser",
                        "checked": null
                    },
                    {
                        "label": "AG4140 Concrete Cleaner",
                        "value": "AG4140 Concrete Cleaner",
                        "checked": null
                    },
                    {
                        "label": "AG4150 Immersion Degreaser",
                        "value": "AG4150 Immersion Degreaser",
                        "checked": null
                    },
                    {
                        "label": "AG4160 Parts Washing Degreaser",
                        "value": "AG4160 Parts Washing Degreaser",
                        "checked": null
                    },
                    {
                        "label": "AG4175 Ink and Coating Remover",
                        "value": "AG4175 Ink and Coating Remover",
                        "checked": null
                    },
                    {
                        "label": "AG4100 All Purpose Cleaner",
                        "value": "AG4100 All Purpose Cleaner",
                        "checked": null
                    },
                    {
                        "label": "AG4120 Heavy Duty Industrial Floor Cleaner",
                        "value": "AG4120 Heavy Duty Industrial Floor Cleaner",
                        "checked": null
                    },
                    {
                        "label": "AG4135 Fleet Wash Industrial Cleaner",
                        "value": "AG4135 Fleet Wash Industrial Cleaner",
                        "checked": null
                    },
                    {
                        "label": "AC-10 Rust Remover & Metal Prep",
                        "value": "AC-10 Rust Remover & Metal Prep",
                        "checked": null
                    },
                    {
                        "label": "AC-22 Scale Remover",
                        "value": "AC-22 Scale Remover",
                        "checked": null
                    },
                    {
                        "label": "AC-30 De-Smutting Cleaner",
                        "value": "AC-30 De-Smutting Cleaner",
                        "checked": null
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "id": "f15",
            "cid": "c46"
        },
        {
            "label": "To determine quantity what will this sample be used for?",
            "field_type": "paragraph",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "size": "small",
                "validators": {
                    "required": {
                        "enabled": false
                    }
                }
            },
            "cid": "c71",
            "id": "f19"
        },
        {
            "label": "Sample #2",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "- None -",
                        "value": "None",
                        "checked": false
                    },
                    {
                        "label": "AG4015 Aircraft Exterior Cleaner",
                        "checked": false,
                        "value": "AG4015 Aircraft Exterior Cleaner"
                    },
                    {
                        "label": "AG4025 Airport High Pressure Cleaner",
                        "checked": false,
                        "value": "AG4025 Airport High Pressure Cleaner"
                    },
                    {
                        "label": "AG4025 Mold, Mildew and Algae Cleaner",
                        "checked": false,
                        "value": "AG4025 Mold, Mildew and Algae Cleaner"
                    },
                    {
                        "label": "AG4035 Runway Rubber Remover",
                        "value": "AG4035 Runway Rubber Remover",
                        "checked": null
                    },
                    {
                        "label": "AG4065 RTU Aircraft Exterior Cleaner",
                        "value": "AG4065 RTU Aircraft Exterior Cleaner",
                        "checked": null
                    },
                    {
                        "label": "AG4110 Paint Prep",
                        "value": "AG4110 Paint Prep",
                        "checked": null
                    },
                    {
                        "label": "AG4125 Original Cleaner-Degreaser",
                        "value": "AG4125 Original Cleaner-Degreaser",
                        "checked": null
                    },
                    {
                        "label": "AG4130 High Pressure Cleaner-Degreaser",
                        "value": "AG4130 High Pressure Cleaner-Degreaser",
                        "checked": null
                    },
                    {
                        "label": "AG4140 Concrete Cleaner",
                        "value": "AG4140 Concrete Cleaner",
                        "checked": null
                    },
                    {
                        "label": "AG4150 Immersion Degreaser",
                        "value": "AG4150 Immersion Degreaser",
                        "checked": null
                    },
                    {
                        "label": "AG4160 Parts Washing Degreaser",
                        "value": "AG4160 Parts Washing Degreaser",
                        "checked": null
                    },
                    {
                        "label": "AG4175 Ink and Coating Remover",
                        "value": "AG4175 Ink and Coating Remover",
                        "checked": null
                    },
                    {
                        "label": "AG4100 All Purpose Cleaner",
                        "value": "AG4100 All Purpose Cleaner",
                        "checked": null
                    },
                    {
                        "label": "AG4120 Heavy Duty Industrial Floor Cleaner",
                        "value": "AG4120 Heavy Duty Industrial Floor Cleaner",
                        "checked": null
                    },
                    {
                        "label": "AG4135 Fleet Wash Industrial Cleaner",
                        "value": "AG4135 Fleet Wash Industrial Cleaner",
                        "checked": null
                    },
                    {
                        "label": "AC-10 Rust Remover & Metal Prep",
                        "value": "AC-10 Rust Remover & Metal Prep",
                        "checked": null
                    },
                    {
                        "label": "AC-22 Scale Remover",
                        "value": "AC-22 Scale Remover",
                        "checked": null
                    },
                    {
                        "label": "AC-30 De-Smutting Cleaner",
                        "value": "AC-30 De-Smutting Cleaner",
                        "checked": null
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c52",
            "id": "f16"
        },
        {
            "label": "To determine quantity what will this sample be used for?",
            "field_type": "paragraph",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "size": "small"
            },
            "cid": "c77",
            "id": "f20"
        },
        {
            "label": "Sample #3",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "- None -",
                        "value": "None",
                        "checked": false
                    },
                    {
                        "label": "AG4015 Aircraft Exterior Cleaner",
                        "checked": false,
                        "value": "AG4015 Aircraft Exterior Cleaner"
                    },
                    {
                        "label": "AG4025 Airport High Pressure Cleaner",
                        "checked": false,
                        "value": "AG4025 Airport High Pressure Cleaner"
                    },
                    {
                        "label": "AG4025 Mold, Mildew and Algae Cleaner",
                        "checked": false,
                        "value": "AG4025 Mold, Mildew and Algae Cleaner"
                    },
                    {
                        "label": "AG4035 Runway Rubber Remover",
                        "value": "AG4035 Runway Rubber Remover",
                        "checked": null
                    },
                    {
                        "label": "AG4065 RTU Aircraft Exterior Cleaner",
                        "value": "AG4065 RTU Aircraft Exterior Cleaner",
                        "checked": null
                    },
                    {
                        "label": "AG4110 Paint Prep",
                        "value": "AG4110 Paint Prep",
                        "checked": null
                    },
                    {
                        "label": "AG4125 Original Cleaner-Degreaser",
                        "value": "AG4125 Original Cleaner-Degreaser",
                        "checked": null
                    },
                    {
                        "label": "AG4130 High Pressure Cleaner-Degreaser",
                        "value": "AG4130 High Pressure Cleaner-Degreaser",
                        "checked": null
                    },
                    {
                        "label": "AG4140 Concrete Cleaner",
                        "value": "AG4140 Concrete Cleaner",
                        "checked": null
                    },
                    {
                        "label": "AG4150 Immersion Degreaser",
                        "value": "AG4150 Immersion Degreaser",
                        "checked": null
                    },
                    {
                        "label": "AG4160 Parts Washing Degreaser",
                        "value": "AG4160 Parts Washing Degreaser",
                        "checked": null
                    },
                    {
                        "label": "AG4175 Ink and Coating Remover",
                        "value": "AG4175 Ink and Coating Remover",
                        "checked": null
                    },
                    {
                        "label": "AG4100 All Purpose Cleaner",
                        "value": "AG4100 All Purpose Cleaner",
                        "checked": null
                    },
                    {
                        "label": "AG4120 Heavy Duty Industrial Floor Cleaner",
                        "value": "AG4120 Heavy Duty Industrial Floor Cleaner",
                        "checked": null
                    },
                    {
                        "label": "AG4135 Fleet Wash Industrial Cleaner",
                        "value": "AG4135 Fleet Wash Industrial Cleaner",
                        "checked": null
                    },
                    {
                        "label": "AC-10 Rust Remover & Metal Prep",
                        "value": "AC-10 Rust Remover & Metal Prep",
                        "checked": null
                    },
                    {
                        "label": "AC-22 Scale Remover",
                        "value": "AC-22 Scale Remover",
                        "checked": null
                    },
                    {
                        "label": "AC-30 De-Smutting Cleaner",
                        "value": "AC-30 De-Smutting Cleaner",
                        "checked": null
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "cid": "c58",
            "id": "f17"
        },
        {
            "label": "To determine quantity what will this sample be used for?",
            "field_type": "paragraph",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "size": "small"
            },
            "id": "f18",
            "cid": "c66"
        },
        {
            "label": "Preferred Shipping Method:",
            "field_type": "dropdown",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "- None -",
                        "value": "None",
                        "checked": false
                    },
                    {
                        "label": "Fed-Ex",
                        "checked": false,
                        "value": "Fed-Ex"
                    },
                    {
                        "label": "UPS",
                        "checked": false,
                        "value": "UPS"
                    }
                ],
                "include_blank_option": false,
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    }
                },
                "presetJson": "",
                "multiple": false
            },
            "id": "f23",
            "cid": "c95",
            "labelHide": false
        },
        {
            "label": "FedEx\/UPS Number:",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "size": "small",
                "addon": []
            },
            "id": "f22",
            "cid": "c90"
        },
        {
            "label": "Submit Button",
            "field_type": "submit",
            "required": true,
            "field_options": {
                "page": {
                    "title": "Submit",
                    "labelPrev": "< Back",
                    "showPageNumnber": false,
                    "pageNumberText": "{page} \/ {total}"
                },
                "images": {
                    "urls": "",
                    "slideshow": false
                }
            },
            "labelHide": true,
            "submit": {
                "label": "",
                "icon": "",
                "checkRequiredFields": ""
            },
            "id": "f0",
            "cid": "c0"
        }
    ],
    "gdpr": {
        "consentFieldId": "",
        "saveData": "no"
    },
    "licenseKey": "JF-26B14737UG7738843"
}
<?php /**JSON_END**/

        $json = ob_get_clean() ;

        return $decode ? json_decode( trim($json), true ) : $json;
    } // end of getConfig()

    private static function getValue( $fieldId, $default = NULL ){
        return isset( $_POST[$fieldId] ) ? $_POST[$fieldId] : $default ;
    }

    private static function overwriteConfig(){
    	//self::get_to();
    }

    private static function get_to(){
    	$value = self::getValue( 'c25' );
    	$to = array(
    		'Option 1' => 'a@a.com',
    		'Option 2' => 'b@b.com',
    		'Option 3' => 'c@c.com',
    	);

    	if( isset( $to[$value] ) ){
    		self::$config['email']['to'] = $to[ $value ];
    	};
    }

} // end of Config class